# Generated by Django 3.2.6 on 2021-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanager', '0002_rename_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
